[book]
authors     = ["Larry Engineer <gm@larry.engineer>"]
description = "Opinionated template for multi-crate Rust projects"
language    = "en"
src         = "book/"
title       = "Rust Template"

[output.html]
additional-js      = ["book/mermaid-init.js"]
git-repository-url = "https://github.com/larry0x/rust"
theme              = "book/theme"

[build]
build-dir = "target/book/"

[rust]
edition = "2024"

# This is for Latex support, install with: `cargo install mdbook-katex@0.10.0-alpha`.
[preprocessor.katex]

# This is for Mermaid diagram support, install with: `cargo install mdbook-mermaid@0.17.0`.
[preprocessor.mermaid]
command = "mdbook-mermaid"
